### ISSUE TITLE
Running new epitweetr version on VM on Azure cloud

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#58]
I am getting the following error when try to activate the database:
epitweetr::fs_loop('E:/Twitter')
Launching fs
Exception in thread "main" java.lang.NoClassDefFoundError: akka/http/scaladsl/model/ContentType
	at org.ecdc.twitter.Tweets$.main(Tweets.scala:31)
	at org.ecdc.twitter.Tweets.main(Tweets.scala)
Caused by: java.lang.ClassNotFoundException: akka.http.scaladsl.model.ContentType
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more
The epitweetr Scala API was stopped with the following error
Error in spark_job(paste("fsService", "epiHome", conf$data_dir)): Error encountered while exeuting:  
"C:\Program Files\Java\jre1.8.0_311\bin\java" -cp "C:/Users/azaghlool/Documents/R/win-library/4.1/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;E:/Twitter/jars/*" -Xmx4g  org.ecdc.twitter.Tweets fsService epiHome E:/Twitter

launching it again within 5 seconds
Exception in thread "main" java.lang.NoClassDefFoundError: akka/actor/ClassicActorSystemProvider
	at org.ecdc.twitter.Tweets$.main(Tweets.scala:31)
	at org.ecdc.twitter.Tweets.main(Tweets.scala)
Caused by: java.lang.ClassNotFoundException: akka.actor.ClassicActorSystemProvider
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more
The epitweetr Scala API was stopped with the following error
Error in spark_job(paste("fsService", "epiHome", conf$data_dir)): Error encountered while exeuting:  
"C:\Program Files\Java\jre1.8.0_311\bin\java" -cp "C:/Users/azaghlool/Documents/R/win-library/4.1/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;E:/Twitter/jars/*" -Xmx4g  org.ecdc.twitter.Tweets fsService epiHome E:/Twitter

launching it again within 5 seconds

**Comment by Abdouzster** [comment]
downloaded dependencies which solved this problem. I will keep this issue until I run this version successfully.

**Comment by Abdouzster** [comment]
I am getting error when trying to run the database
 epitweetr::fs_loop(' E:/Twitter ')
Launching fs
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file ' E:/Twitter /fs.PID': Invalid argument

**Comment by Abdouzster** [comment]
Now it shows me the following warning:
> epitweetr::fs_loop('E:/Twitter')
Launching fs
[WARN] [04/01/2022 09:55:01.897] [epitweetr-akka.actor.default-dispatcher-14] [akka.actor.ActorSystemImpl(epitweetr)] Illegal header: Illegal 'user-agent' header: Invalid input ';', expected OWS, product-or-comment or 'EOI' (line 1, column 31): RStudio Desktop (2022.2.1.461); R (4.1.3 x86_64-w64-mingw32 x86_64 mingw32)

**Comment by Abdouzster** [comment]
the search loop stopped and I removed all data to skip migration but the it is still giving me the following message at dependencies
Search loop is currently running. Migrating from previous version storage is not supported while search loop is running. Please deactivate it

**Comment by Abdouzster** [comment]
I started in a new home directory. all is working now but still have alert failure with the following error
2022-04-01 15:57:52 : Executing task alerts
Cannot determine the last aggregated period for alert detection, tryng again in 0  seconds
Cannot determine the last aggregated period for alert detection, tryng again in 10  seconds
Cannot determine the last aggregated period for alert detection, tryng again in 20  seconds
Cannot determine the last aggregated period for alert detection, tryng again in 30  seconds
Failed...
failed while processing  : Error in do_next_alerts(tasks): Cannot determine the last aggregated period for alert detection. Please check that series have been aggregated

**Comment by lauespinosa** [comment]
> I am getting error when trying to run the database epitweetr::fs_loop(' E:/Twitter ') Launching fs Error in file(file, ifelse(append, "a", "w")) : cannot open the connection In addition: Warning message: In file(file, ifelse(append, "a", "w")) : cannot open file ' E:/Twitter /fs.PID': Invalid argument

The issue here may be the additional spaces between the single quotation marks and the path. It should be 'E:/Twitter' instead of ' E:/Twitter '.

**Comment by lauespinosa** [comment]
> Now it shows me the following warning:
> 
> > epitweetr::fs_loop('E:/Twitter')
> > Launching fs
> > [WARN] [04/01/2022 09:55:01.897] [epitweetr-akka.actor.default-dispatcher-14] [akka.actor.ActorSystemImpl(epitweetr)] Illegal header: Illegal 'user-agent' header: Invalid input ';', expected OWS, product-or-comment or 'EOI' (line 1, column 31): RStudio Desktop (2022.2.1.461); R (4.1.3 x86_64-w64-mingw32 x86_64 mingw32)

A warning shouldn't stop the database. Was the database (fs_loop) stopped or showing any error?

**Comment by lauespinosa** [comment]
> the search loop stopped and I removed all data to skip migration but the it is still giving me the following message at dependencies Search loop is currently running. Migrating from previous version storage is not supported while search loop is running. Please deactivate it

For migrating data from epitweetr v1 to v2, you need to activate and deactivate the pipelines as indicated in the messages. It was required to stop the search loop in order to continue with the migration.

**Comment by Abdouzster** [comment]
It is showing me that error on alerting still: Max number of retries reached failed while processing alerts Error in do_next_alerts(tasks): Cannot determine the last aggregated period for alert detection. Please check that series have been aggregated
In the diagnostics the aggregation is false: No aggregated series found. Please run the search loop to collect and aggregate data
As I indicated in another issue, the fs sub folders were not created. it is only tweets folder. It is accumulating tweets for 3 weeks but no aggregation happening.

**Comment by Abdouzster** [comment]
There is a search loop error appearing now:
2022-04-05 11:15:55 [INFO]: -------> searching for topic Measles from 1511320866403061764 until (last tweet)
retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Error in value[[3L]](cond) : 
  $ operator is invalid for atomic vectors Error: $ operator is invalid for atomic vectors

**Comment by Abdouzster** [comment]
Now error in the search loop:

[1] "{\"dates\":[],\"msg\":\"One of the geolocacing or aggregating files in geo folder is bigger than the pred"
2022-04-05 13:33:19 [INFO]: -------> Error found while sending tweets Error in doTryCatch(return(expr), name, parentenv, handler): 

[1] "{\"dates\":[],\"msg\":\"One of the geolocacing or aggregating files in geo folder is bigger than the pred"
2022-04-05 13:33:19 [INFO]: -------> Error found while sending tweets Error in doTryCatch(return(expr), name, parentenv, handler): 

Error in value[[3L]](cond) : 
  too many retries Error in value[[3L]](cond): too many retries
> epitweetr::search_loop('E:/Twitter22')
2022-04-05 13:34:57 [INFO]: -------> searching for topic Measles from 1511362324845805572 until (last tweet)
[1] "{\"dates\":[],\"msg\":\"One of the geolocacing or aggregating files in geo folder is bigger than the pred"
2022-04-05 13:34:58 [INFO]: -------> Error found while sending tweets Error in doTryCatch(return(expr), name, parentenv, handler): 

[1] "{\"dates\":[],\"msg\":\"One of the geolocacing or aggregating files in geo folder is bigger than the pred"
2022-04-05 13:34:58 [INFO]: -------> Error found while sending tweets Error in doTryCatch(return(expr), name, parentenv, handler): 

[1] "{\"dates\":[],\"msg\":\"One of the geolocacing or aggregating files in geo folder is bigger than the pred"
2022-04-05 13:34:58 [INFO]: -------> Error found while sending tweets Error in doTryCatch(return(expr), name, parentenv, handler): 

[1] "{\"dates\":[],\"msg\":\"One of the geolocacing or aggregating files in geo folder is bigger than the pred"
2022-04-05 13:34:58 [INFO]: -------> Error found while sending tweets Error in doTryCatch(return(expr), name, parentenv, handler): 

Error in value[[3L]](cond) : 
  too many retries Error in value[[3L]](cond): too many retries

**Comment by Abdouzster** [comment]
Complete! Processed total of 6 rows.
Sending alert to  zaghloola@yahoo.com
Error when sending email Error in `stop_rate_excess()`:
! Request failed after 5 attempts

Failed...
failed while sending emails  : Error in `stop_rate_excess()`:
! Request failed after 5 attempts

2022-04-10 13:29:31 : Executing task alerts
Adding topwords
Adding hashtags
Adding urls
Adding contexts
Adding entities
Complete! Processed total of 8 rows.
Sending alert to  zaghloola@yahoo.com
Error when sending email Error in `stop_rate_excess()`:
! Request failed after 5 attempts

Failed...
failed while sending emails  : Error in `stop_rate_excess()`:
! Request failed after 5 attempts

2022-04-11 08:59:42 : Executing task alerts

**Comment by forchard** [comment]
HI @Abdouzster 
It seems the issue comes from your smtp configuration 
Can you try this code and share the results?
> \`%>%\` <- magrittr::\`%>%\`
> dest = "your@email.here"
> html <- "\<html\>\<body\>\<table style=\\"border:1px solid black;width:100%;border-collapse:collapse;background-color:#BBBBBB\\"\>\<tr\>\<td\>Column 1\</td\>\<td\>Column 2\</td\>\</tr\>\</table\>\</body\>\</html\>"
> msg <- (emayili::envelope() %>% emayili::from(epitweetr:::conf$smtp_from) %>% emayili::to(dest) %>% emayili::subject("Hi there!") %>% emayili::html(html))
> smtp <- emayili::server(host = epitweetr:::conf$smtp_host, port=epitweetr:::conf$smtp_port, username=epitweetr:::conf$smtp_login, insecure=epitweetr:::conf$smtp_insecure, password=epitweetr:::conf$smtp_password, reuse = FALSE)
> smtp(msg)

Thanks!
Francisco

**Comment by Abdouzster** [comment]
fs loop error
2022-04-11 10:59:32[INFO]---->Error during geolocalisation: key not found: Meningococcal disease: scala.collection.MapLike.default(MapLike.scala:235)

**Comment by forchard** [comment]
Hi @Abdouzster,
Can we focus on the email sent error you just reported?
Then we can move to other issues.
Best,
Francisco

**Comment by Abdouzster** [comment]
Hi Francisco,
I was focusing on having a running version on a clean directory. I was finally able to do so on Thursday. I will try the email may be next week when I have a chance. I didn't add email to this working version yet.
The search loop working fine from the activate button but some time it stops. when I try it manually it gives me the following error.

2022-04-15 09:55:45 [INFO]: -------> searching for topic Measles from 1514946110363635715 until (last tweet)
Requesting token on behalf of user...
Error in value[[3L]](cond) : 
  schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted. Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Thanks,
Abdelhamid

**Comment by Abdouzster** [comment]
The Twitter application endpoint  1.1 is about to reach its rate limit, changing endpoint to another available version
The Twitter application endpoint  1.1 has reached its rate limit, waiting 775 seconds  until 2022-04-15 11:43:57 as requested by twitter
retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Error in value[[3L]](cond) : 
  $ operator is invalid for atomic vectors Error: $ operator is invalid for atomic vectors

**Comment by Abdouzster** [comment]
The Twitter application endpoint  1.1 is about to reach its rate limit, changing endpoint to another available version
The Twitter application endpoint  1.1 has reached its rate limit, waiting 756 seconds  until 2022-04-16 13:46:41 as requested by twitter
retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

retrying because of error  Error in curl::curl_fetch_memory(url, handle = handle): schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Error in value[[3L]](cond) : 
  $ operator is invalid for atomic vectors Error: $ operator is invalid for atomic vectors

**Comment by forchard** [comment]
Hi @Abdouzster,
Same question made on the issue https://github.com/EU-ECDC/epitweetr/issues/61:

Are you still getting this error? At a first glance it seems to be an issue on authenticating the Twitter endpoint.

A few questions:

- Are you going through a proxy https://www.whatismyip.com/proxy-check/ and https://www.howtogeek.com/207051/how-to-tell-whether-your-windows-pc-is-using-a-proxy-server/
- In order to try to reproduce the error can you try the following code?
> epitweetr::setup_config("your data folder here")
resp = epitweetr:::twitter_search("epitweetr", count = 10)

Thanks!
Francisco
