### ISSUE TITLE
Database error preventing the aggregation

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#65]
epitweetr::fs_loop('E:/Twitter2022')
Launching fs
[ERROR] [05/13/2022 08:36:54.901] [epitweetr-akka.actor.internal-dispatcher-3] [akka://epitweetr/system/IO-TCP/selectors/$a/0] Bind failed for TCP channel on endpoint [localhost/127.0.0.1:8080]
java.net.BindException: [localhost/127.0.0.1:8080] Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
	at akka.io.TcpListener.<init>(TcpListener.scala:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at akka.util.Reflect$.instantiate(Reflect.scala:73)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
	at akka.actor.ActorCell.create(ActorCell.scala:640)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by Abdouzster** [comment]
I had to reset the VM for it to resolve
